#!/usr/bin/env zsh


# shellcheck disable=2296
NAME=$(basename "${(%):-%N}")

ROOT=${0:A:h:h}
TMP="$ROOT/tmp"

debug=""


function prepare_test {
    mkdir -p "$TMP"
}


function from_prompts {
    uv run pqr $debug prompts                             \
        --output "$TMP"                                   \
        --encoding "compact"                              \
        --add-caption                                     \
        --add-date                                        \
        --date-template "%Y-%m"                           \
        --filename-template "{filament-name}-{date}"      \
        --filename-transformation "to-ascii"              \
        --filename-transformation "to-lowercase"          \
        --filename-transformation "spaces-to-underscores" \
        --caption-templates "{filament-name}" "{date}"
}


function from_args {
    uv run pqr $debug args                                \
        --output "$TMP"                                   \
        --encoding "compact"                              \
        --add-caption                                     \
        --add-date                                        \
        --date-template "%Y-%m"                           \
        --filename-template "{filament-name}-{date}"      \
        --filename-transformation "to-ascii"              \
        --filename-transformation "to-lowercase"          \
        --filename-transformation "spaces-to-underscores" \
        --caption-templates "{filament-name}" "{date}"    \
                                                          \
        --filament-name               "FILAMENT_NAME"     \
        --filament-brand              "FILAMENT_BRAND"    \
        --filament-material           "FILAMENT_MATERIAL" \
                                                          \
        --printer-name                "PRINTER_NAME"      \
        --printer-nozzle-size         99.9                \
        --printer-nozzle-type         "NOZZLE_TYPE"       \
                                                          \
        --slicer-name                 "SLICER_NAME"       \
        --slicer-setting-preset       "SETTING_PRESET"    \
        --slicer-filament-preset      "FILAMENT_PRESET"   \
        --slicer-printer-preset       "PRINTER_PRESET"    \
        --slicer-max-volumetric-speed 999                 \
        --slicer-layer-height         99.9                \
        --slicer-nozzle-temp          999                 \
        --slicer-bed-temp             999                 \
        --slicer-print-time           "99:59"             \
                                                          \
        --misc-notes                  "MISC_NOTES"
}


function from_template {
    uv run pqr $debug template                             \
        "${ROOT}/src/pqr/tests/template-data.toml"         \
        --output "$TMP"                                    \
        --encoding "compact"                               \
        --add-caption                                      \
        --add-date                                         \
        --date-template "%Y-%m"                            \
        --filename-template "{filament-name}-{date}"       \
        --filename-transformation "to-ascii"               \
        --filename-transformation "to-lowercase"           \
        --filename-transformation "spaces-to-underscores"  \
        --caption-templates "{filament-name}" "{date}"
}


function print_help {
    echo -e "Test run PrintQR.

\e[4mUsage:\e[0m ${NAME} [OPTIONS] <COMMAND> [--debug/-d]

\e[4mCommands:\e[0m
  prompts   Run test using the 'prompts' command
  args      Run test using the 'args' command
  template  Run test using the 'template' command

\e[4mOptions:\e[0m
  -d, --debug  Run in debug mode
  -h, --help   Show help"
}


function main {

    if [[ "$1" == "--help" || "$1" == "-h" ]]; then
        print_help
        exit 0
    fi

    if [[ $# -ne 1 ]]; then
        echo "Error: missing required positional argument 'command'"
        print_help
        exit 1
    fi

    if [[ "$2" == "--debug" || "$2" == "-d" ]]; then
        debug="--debug"
    fi

    case "$1" in
        "prompts")
            prepare_test
            from_prompts
            ;;
        "args")
            prepare_test
            from_args
            ;;
        "template")
            prepare_test
            from_template
            ;;
        *)
            echo "Error: invalid command '$1'"
            print_help
            exit 1
            ;;
    esac
}


main "$@"
